// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcwnjxgfbbqnpbexydcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jd25qeGdmYmJxbnBiZXh5ZGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MTY1MDYsImV4cCI6MjA3MzQ5MjUwNn0.bWkeYELIHmpN7_n3nSezg1W_ndy4G5g6NoE73uL1ipM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});